# Site settings
title: OpenMapKit
email: 
description: > # this means to ignore newlines until "baseurl:"
  OpenMapKitWebsite is the website for the OpenMapKit project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openmapkit.org/" # the base hostname & protocol for your site
twitter_username: awesomeposm
github_username:  AmericanRedCross

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Plugins
gems: ["jekyll-paginate", "rouge", "kramdown","jekyll-watch", "markdown"]
