# Site settings
title: OpenMapKit Website
email: info@openmapkit.org
description: > # this means to ignore newlines until "baseurl:"
  OpenMapKitWebsite is the website for the OpenMapKit project. We are moving all training
  material within the wiki to the website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openmapkit.org/" # the base hostname & protocol for your site
twitter_username: OpenMapKit
github_username:  AmericanRedCross

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Plugins
gems: ["jekyll-paginate", "rouge", "kramdown","jekyll-watch", "markdown"]
